### ISSUE TITLE
[Question] Does this version of shadowsocks support udp forwarding using simple obfs?

### ISSUE THREAD

**Issue by shadowmigue** [primovist/shadowsocks-libev.simple-obfs#1]
Like the tittle say i want to know if it supprot it and how i can install it on ubuntu 18

Regards,
ShadowMigue

**Comment by primovist** [comment]
所有功能参见shadowsocks-libev，端口映射做好了是支持UDP的。

发自我的 iPhone

在 2019年3月24日，22:42，shadowmigue <notifications@github.com<mailto:notifications@github.com>> 写道：


Like the tittle say i want to know if it supprot it and how i can install it on ubuntu 18

Regards,
ShadowMigue

**Comment by shadowmigue** [comment]
Can you addme on telegram so i can ask you a few more question?
@miguespark

Regards,
ShadowMigue
